# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain


endpoints:
  shutdown:
    enabled:  true
  restart:
    enabled: true


spring:
  h2:
    console:
      enabled: true

  # Datasource
  # H2 Console http://localhost:8080/h2-console
  # JDBC URL jdbc:h2:file:./testdb
  datasource:
    url:
      #jdbc:h2:file:./testdb;DB_CLOSE_ON_EXIT=FALSE;
      jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;
    username:
      sa
    password:
    driver-class-name:
      org.h2.Driver

  jpa:
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.H2Dialect